project:
  type: book
  output-dir: "."

book:
  title: "Prep Materials"
  author: "Abdullah Al Mahmud"
  date: "4/3/2025"
  page-navigation: true
  chapters:
    - index.qmd
    - gre-short-passage.qmd
    - gre-word-list.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo




