project:
  type: website
  output-dir: "."

website:
  title: "GRE Prep"
  navbar:
    background: light
    logo: ../assets/images/logo.png
    logo-alt: "Stat Mania logo."
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: gre-word-list.qmd
        text: Word List
      - href: gre-short-passage.qmd
        text: Passages
      - text: "Flashcards"
        href: gre-flashcards.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



