project:
  type: website
  output-dir: "."

website:
  title: "GRE Prep"
  navbar:
    background: light
    logo: ../assets/images/logo.png
    logo-alt: "Stat Mania logo."
    title: Stat Mania GRE
    left:
      - href: index.qmd
        text: Home
      - href: gre-word-list.qmd
        text: Word List
      - href: gre-short-passage.qmd
        text: Passages
      - href: stories.qmd
        text: Stories
      - text: "Flashcards"
        href: gre-flashcards.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Verbal"
        contents:
          - text: Word List
            href: gre-word-list.qmd
          - text: Passages
            href: gre-short-passage.qmd
          - text: Stories
            href: stories.qmd

      - section: "Quant"
        contents:
          - text: Data Interpretation
            href: gre-quant-data.qmd
format:
  html:
    theme: literal
    css: styles.css
    toc: true



