project:
  type: website
  output-dir: "."

website:
  title: "GRE Prep"
  navbar:
    background: light
    logo: ../assets/images/logo.png
    logo-alt: "Stat Mania logo."
    title: Stat Mania GRE
    left:
      - href: index.qmd
        text: Home
      - href: gre-word-list.qmd
        text: Word List
      - href: gre-short-passage.qmd
        text: Passages
      - href: stories.qmd
        text: Stories
      - text: "Flashcards"
        href: gre-flashcards.qmd
  sidebar:
    title: Prep
    style: "floating"
    collapse-level: 2
    align: left
    contents:
      - text: "Home"
        href: index.qmd
        contents:
          - section: "Verbal"
            contents:
              - text: Word List
                href: gre-word-list.qmd
              - text: Passages
                href: gre-short-passage.qmd
              - text: Stories
                href: stories.qmd

          - section: "Quant"
            contents:
              - text: Data Interpretation
                href: gre-quant-data.qmd
              - text: Combinatorics and Probability
                href: gre-quant-prob.qmd
format:
  html:
    theme: literal
    css: styles.css
    toc: true



